version: "3.9"
 
services:
  db:
    image: postgis/postgis:17-3.5
    container_name: postgis-db
    restart: always
    environment:
      POSTGRES_DB: road_network
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  backend:
    build:
      context: .
    container_name: fastapi-app
    restart: always
    command: 
      - uvicorn
      - app.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/road_network
volumes:
  pgdata: